import 'server-only';
import { randomBytes } from 'crypto';
import { createClient } from './supabase/server';
import { optimizeRoutes, type Stop, type Vehicle } from './optimizer';

// @supabase/ssr 0.5.2's typing chokes on the new __InternalSupabase root key
// generated by `supabase gen types` (introduced for postgrest 13/14 features).
// Cast only at this seam — the explicit return types on every exported function
// keep the public surface fully typed.
type SupabaseLoose = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  from: (table: string) => any;
  rpc: (fn: string, args?: Record<string, unknown>) => Promise<{ data: unknown; error: { message: string } | null }>;
};

export type RouteStop = {
  seq: number;
  binId: string;
  address: string | null;
  lat: number;
  lng: number;
  fillPct: number;
  kind: 'public' | 'household';
};

export type GeneratedRoute = {
  id: string;
  vehicleId: string;
  vehicleLabel: string;
  driverToken: string;
  plannedFor: string;
  stops: RouteStop[];
  distanceM: number;
  durationS: number;
};

export type RipeBin = {
  id: string;
  lat: number;
  lng: number;
  fillPct: number;
  address: string | null;
  kind: 'public' | 'household';
};

type VehicleWithPosition = {
  id: string;
  label: string;
  lat: number;
  lng: number;
  capacityKg: number;
};

const AVG_SPEED_MPS = 30 / 3.6; // 30 km/h average through urban streets

export async function getRipeBins(): Promise<RipeBin[]> {
  const supabase = createClient() as unknown as SupabaseLoose;
  const { data, error } = await supabase.rpc('ripe_bins_for_routing');
  if (error) throw new Error(error.message);
  return ((data as Record<string, unknown>[] | null) ?? []).map((row) => ({
    id: row.id as string,
    lat: row.lat as number,
    lng: row.lng as number,
    fillPct: row.fill_pct as number,
    address: (row.address as string | null) ?? null,
    kind: row.kind as 'public' | 'household',
  }));
}

export async function getActiveVehiclesWithPosition(): Promise<VehicleWithPosition[]> {
  const supabase = createClient() as unknown as SupabaseLoose;
  const { data, error } = await supabase.rpc('vehicles_with_latest_position');
  if (error) throw new Error(error.message);
  return ((data as Record<string, unknown>[] | null) ?? []).map((row) => ({
    id: row.id as string,
    label: row.label as string,
    capacityKg: row.capacity_kg as number,
    lat: (row.lat as number) ?? 50.5942,
    lng: (row.lng as number) ?? 32.3874,
  }));
}

export async function generateTodayRoutes(communityId: string): Promise<GeneratedRoute[]> {
  const supabase = createClient() as unknown as SupabaseLoose;
  const [bins, vehicles] = await Promise.all([
    getRipeBins(),
    getActiveVehiclesWithPosition(),
  ]);
  if (bins.length === 0 || vehicles.length === 0) return [];

  const stops: Stop[] = bins.map((b) => ({
    id: b.id,
    lat: b.lat,
    lng: b.lng,
    priority: b.fillPct,
  }));
  const vrpVehicles: Vehicle[] = vehicles.map((v) => ({
    id: v.id,
    startLat: v.lat,
    startLng: v.lng,
    capacity: v.capacityKg,
  }));

  const plans = optimizeRoutes(stops, vrpVehicles);
  const today = new Date().toISOString().slice(0, 10);
  const result: GeneratedRoute[] = [];

  for (const plan of plans) {
    if (plan.stops.length === 0) continue;
    const vehicle = vehicles.find((v) => v.id === plan.vehicleId);
    if (!vehicle) continue;

    const driverToken = randomBytes(8).toString('hex');
    const stopsPayload: RouteStop[] = plan.stops.map((s, i) => {
      const bin = bins.find((b) => b.id === s.id);
      return {
        seq: i + 1,
        binId: s.id,
        address: bin?.address ?? null,
        lat: s.lat,
        lng: s.lng,
        fillPct: bin?.fillPct ?? 0,
        kind: bin?.kind ?? 'public',
      };
    });

    // LINESTRING WKT: depot start → every stop, in tour order.
    const coords = [
      `${vehicle.lng} ${vehicle.lat}`,
      ...plan.stops.map((s) => `${s.lng} ${s.lat}`),
    ];
    const lineWkt = `SRID=4326;LINESTRING(${coords.join(', ')})`;

    const { data: inserted, error: routeErr } = await supabase
      .from('routes')
      .insert({
        community_id: communityId,
        vehicle_id: plan.vehicleId,
        planned_for: today,
        stops: stopsPayload as never,
        geometry: lineWkt as unknown as string,
        distance_m: plan.distanceM,
        duration_s: Math.round(plan.distanceM / AVG_SPEED_MPS),
        status: 'planned',
        driver_token: driverToken,
      })
      .select('id, planned_for')
      .single();

    if (routeErr || !inserted) {
      console.error('insert route failed', routeErr);
      continue;
    }

    result.push({
      id: inserted.id as string,
      vehicleId: plan.vehicleId,
      vehicleLabel: vehicle.label,
      driverToken,
      plannedFor: inserted.planned_for as string,
      stops: stopsPayload,
      distanceM: plan.distanceM,
      durationS: Math.round(plan.distanceM / AVG_SPEED_MPS),
    });
  }
  return result;
}

export async function listRecentRoutes(): Promise<GeneratedRoute[]> {
  const supabase = createClient() as unknown as SupabaseLoose;
  const { data, error } = await supabase
    .from('routes')
    .select('id, vehicle_id, planned_for, stops, distance_m, duration_s, driver_token, vehicles(label)')
    .gte('planned_for', new Date(Date.now() - 7 * 86_400_000).toISOString().slice(0, 10))
    .order('planned_for', { ascending: false })
    .order('generated_at', { ascending: false });
  if (error) throw new Error(error.message);

  return (data ?? []).map((row: Record<string, unknown>) => ({
    id: row.id as string,
    vehicleId: row.vehicle_id as string,
    vehicleLabel:
      ((row.vehicles as Record<string, unknown> | null)?.label as string) ?? 'Машина',
    driverToken: (row.driver_token as string) ?? '',
    plannedFor: row.planned_for as string,
    stops: (row.stops as RouteStop[]) ?? [],
    distanceM: (row.distance_m as number) ?? 0,
    durationS: (row.duration_s as number) ?? 0,
  }));
}
